### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Dark-Star321** [Dark-Star321/Dark-Star321.github.io#2]
issueでいいのかな？「docsフォルダが見つからなくてサイトがビルドできませんでした。」というメールが来たのですが、docsフォルダーが何なのか調べてもわからず、解決法がわかりません。どなたか助けてください...

**Comment by developermodoki** [comment]
エラー内容はどんな感じでしょうか。

**Comment by developermodoki** [comment]
すいません。原因である可能性がある所を見つけました。
まず、index.htmlには
```html
<link rel="stylesheet" href="https://dark-star321.github.io/css/style.css"></link>
```
とありますが、この
```html
</link>
```
は必要ありません。
それに、リンク先も
"https://dark-star321.github.io/css/style.css"
となっていますが、これも問題です。
"/css/style.css"に変更してください。(屁理屈みたいですいません)
さらに、リポジトリ名が"Dark-Star321.github.io"となっていますが、大文字の所があるので、GitHub Pagesとしては認識されない可能性があります。大文字の所を小文字に変更してください。

**Comment by Dark-Star321** [comment]
/linkを消しました。ただ、/linkを消しただけでもgithubから「ページのビルドに失敗しました」というメッセージが来たので一応pagesとして認識されているみたいです。ちなみにエラー内容は上記と同じでした。

**Comment by Dark-Star321** [comment]
`/docs`フォルダを新しく作ってみたら、ページのビルドに成功しました！ただ純粋に`/docs`フォルダを作ればいいだけの話だったみたいです...
